/**
 * Injected into every Boss Built export so ownership is real:
 * README, package.json, gitignore, and GitHub Actions CI.
 */

export function buildExportExtras(name: string, files: Array<{ path: string; content: string }>) {
  const extras: Array<{ path: string; content: string }> = [];
  const has = (p: string) => files.some((f) => f.path === p) || extras.some((f) => f.path === p);

  if (!has("package.json")) {
    extras.push({
      path: "package.json",
      content: JSON.stringify(
        {
          name: name.toLowerCase().replace(/[^a-z0-9-_]/g, "-") || "boss-built-app",
          version: "1.0.0",
          private: true,
          scripts: {
            dev: "vite",
            build: "vite build",
            preview: "vite preview",
          },
          devDependencies: {
            vite: "^6.0.0",
          },
        },
        null,
        2
      ),
    });
  }

  if (!has(".gitignore")) {
    extras.push({
      path: ".gitignore",
      content: `node_modules\ndist\n.env\n.env.*\n!.env.example\n.DS_Store\n.vercel\n`,
    });
  }

  if (!has(".env.example")) {
    extras.push({
      path: ".env.example",
      content: `# Copy to .env and fill in\n# VITE_API_URL=\n`,
    });
  }

  if (!has(".github/workflows/ci.yml")) {
    extras.push({
      path: ".github/workflows/ci.yml",
      content: `name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: |
          if [ -f package.json ]; then
            npm install
            npm run build --if-present
          else
            echo "Static export — no build step"
          fi
`,
    });
  }

  if (!has(".github/workflows/deploy.yml")) {
    extras.push({
      path: ".github/workflows/deploy.yml",
      content: `name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  vercel:
    runs-on: ubuntu-latest
    if: \${{ secrets.VERCEL_TOKEN != '' }}
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Vercel
        run: |
          npx vercel pull --yes --environment=production --token=\${{ secrets.VERCEL_TOKEN }}
          npx vercel build --token=\${{ secrets.VERCEL_TOKEN }}
          npx vercel deploy --prebuilt --prod --token=\${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: \${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: \${{ secrets.VERCEL_PROJECT_ID }}
`,
    });
  }

  if (!has("README.md")) {
    extras.push({
      path: "README.md",
      content: `# ${name}

Generated by **Boss Built** Genesis Swarm.

## Local

\`\`\`bash
npm install
npm run dev
\`\`\`

## Deploy

- **Vercel:** connect this repo or use Boss Built one-click Vercel
- **GitHub Actions:** set \`VERCEL_TOKEN\`, \`VERCEL_ORG_ID\`, \`VERCEL_PROJECT_ID\` secrets, then push to \`main\`

## Ownership

You own this code. No Boss Built runtime lock-in.
`,
    });
  }

  return extras;
}
