/**
 * GitHub: create repo + commit files via Contents API (no git binary required).
 */

export interface GitHubPushResult {
  repoUrl: string;
  owner: string;
  repo: string;
  filesWritten: number;
}

async function gh(
  token: string,
  path: string,
  init: RequestInit = {}
): Promise<Response> {
  return fetch(`https://api.github.com${path}`, {
    ...init,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
      "Content-Type": "application/json",
      ...(init.headers ?? {}),
    },
  });
}

export async function pushToGitHub(opts: {
  token: string;
  name: string;
  description?: string;
  files: Array<{ path: string; content: string }>;
  private?: boolean;
  owner?: string; // if omitted, uses authenticated user
}): Promise<GitHubPushResult> {
  // Who am I?
  const userRes = await gh(opts.token, "/user");
  if (!userRes.ok) {
    throw new Error(`GitHub auth failed: ${userRes.status}`);
  }
  const user = (await userRes.json()) as { login: string };
  const owner = opts.owner ?? user.login;
  const repo = opts.name
    .toLowerCase()
    .replace(/[^a-z0-9-_]/g, "-")
    .replace(/-+/g, "-")
    .slice(0, 100);

  // Create repo (ignore if exists)
  const createRes = await gh(opts.token, "/user/repos", {
    method: "POST",
    body: JSON.stringify({
      name: repo,
      description: opts.description ?? "Generated by Boss Built",
      private: opts.private ?? true,
      auto_init: true,
    }),
  });

  if (!createRes.ok && createRes.status !== 422) {
    const err = await createRes.text();
    throw new Error(`GitHub create repo: ${createRes.status} ${err.slice(0, 300)}`);
  }

  // Wait briefly for empty commit from auto_init
  await new Promise((r) => setTimeout(r, 800));

  let written = 0;
  for (const file of opts.files) {
    const path = file.path.replace(/^\/+/, "");
    const contentB64 = Buffer.from(file.content, "utf8").toString("base64");

    // Get existing sha if file exists
    let sha: string | undefined;
    const getRes = await gh(
      opts.token,
      `/repos/${owner}/${repo}/contents/${encodeURIComponent(path).replace(/%2F/g, "/")}`
    );
    if (getRes.ok) {
      const existing = (await getRes.json()) as { sha?: string };
      sha = existing.sha;
    }

    const putRes = await gh(
      opts.token,
      `/repos/${owner}/${repo}/contents/${path
        .split("/")
        .map(encodeURIComponent)
        .join("/")}`,
      {
        method: "PUT",
        body: JSON.stringify({
          message: `Boss Built: add ${path}`,
          content: contentB64,
          ...(sha ? { sha } : {}),
        }),
      }
    );

    if (!putRes.ok) {
      const err = await putRes.text();
      console.warn(`[github] failed ${path}: ${putRes.status} ${err.slice(0, 200)}`);
      continue;
    }
    written++;
  }

  return {
    repoUrl: `https://github.com/${owner}/${repo}`,
    owner,
    repo,
    filesWritten: written,
  };
}
