/**
 * Boss Built — Deploy package (Phase 4)
 */
export * from "./zip.js";
export * from "./vercel.js";
export * from "./github.js";

export interface DeployFile {
  path: string;
  content: string;
}

export interface ExportBundle {
  name: string;
  files: DeployFile[];
  readme: string;
  createdAt: string;
}

export function buildExportBundle(
  projectName: string,
  files: DeployFile[]
): ExportBundle {
  const safe =
    projectName.replace(/[^a-z0-9-_]+/gi, "-").toLowerCase() || "boss-built-app";
  const readme = `# ${projectName}

Generated by **Boss Built** Genesis Swarm.

## Run

\`\`\`bash
npm install
npm run dev
\`\`\`

---
Boss Built · ownership included
`;

  const hasReadme = files.some((f) => f.path.toLowerCase() === "readme.md");
  const out = hasReadme
    ? files
    : [{ path: "README.md", content: readme }, ...files];

  return {
    name: safe,
    files: out,
    readme,
    createdAt: new Date().toISOString(),
  };
}
