/** Offline demo sequence so Phase 3 UI can be previewed without API */

type Handler = (ev: Record<string, unknown>) => void;

const wait = (ms: number) => new Promise((r) => setTimeout(r, ms));

export async function playDemoSequence(onEvent: Handler) {
  const steps: Array<{ delay: number; ev: Record<string, unknown> }> = [
    { delay: 0, ev: { type: "layer_start", layer: 1, content: "SOVEREIGN online — reviewing your request with you." } },
    {
      delay: 200,
      ev: {
        type: "agent_start",
        agentKey: "sovereign",
        agentName: "SOVEREIGN",
        content:
          "I'm right here with you. Before we commit the swarm, I need to make sure we're building exactly what you want — not what I assume.",
      },
    },
    {
      delay: 800,
      ev: {
        type: "agent_thinking",
        agentKey: "sovereign",
        agentName: "SOVEREIGN",
        content: "Context packed (~900 tokens) · 3 memory hits",
      },
    },
    {
      delay: 1200,
      ev: {
        type: "agent_message",
        agentKey: "sovereign",
        agentName: "SOVEREIGN",
        content:
          "Clear enough. I'm briefing the Architect Council and keeping you in the loop the entire way.",
      },
    },
    { delay: 400, ev: { type: "agent_complete", agentKey: "sovereign", agentName: "SOVEREIGN" } },
    { delay: 200, ev: { type: "layer_complete", layer: 1, content: "SOVEREIGN pass complete." } },
    { delay: 300, ev: { type: "layer_start", layer: 2, content: "Architect Council assembling." } },
    {
      delay: 150,
      ev: {
        type: "agent_start",
        agentKey: "sysarch",
        agentName: "Sys Architect",
        content: "I'm mapping the skeleton of this system so it won't collapse under real users.",
      },
    },
    {
      delay: 150,
      ev: {
        type: "agent_start",
        agentKey: "uxarch",
        agentName: "UX Architect",
        content: "I'm thinking about the human on the other side of the screen.",
      },
    },
    {
      delay: 150,
      ev: {
        type: "agent_start",
        agentKey: "secarch",
        agentName: "Security Architect",
        content: "I'm the paranoid one. If it can be abused, I'll find it first.",
      },
    },
    {
      delay: 900,
      ev: {
        type: "decision",
        agentKey: "sysarch",
        agentName: "Sys Architect",
        content: "Stack: vite-react · express · drizzle · stripe",
      },
    },
    { delay: 200, ev: { type: "agent_complete", agentKey: "sysarch", agentName: "Sys Architect" } },
    { delay: 100, ev: { type: "agent_complete", agentKey: "uxarch", agentName: "UX Architect" } },
    { delay: 100, ev: { type: "agent_complete", agentKey: "secarch", agentName: "Security Architect" } },
    { delay: 200, ev: { type: "layer_complete", layer: 2, content: "Architecture decisions locked." } },
    { delay: 300, ev: { type: "layer_start", layer: 4, content: "Workers executing implementation tasks." } },
    {
      delay: 150,
      ev: {
        type: "agent_start",
        agentKey: "worker",
        agentName: "Worker",
        content: "Executing the concrete work right now.",
      },
    },
    {
      delay: 600,
      ev: {
        type: "file_write",
        agentKey: "worker",
        content: "src/App.tsx",
        data: { path: "src/App.tsx", status: "writing" },
      },
    },
    {
      delay: 900,
      ev: {
        type: "file_write",
        agentKey: "worker",
        content: "src/App.tsx",
        data: {
          path: "src/App.tsx",
          status: "wrote",
          lines: 24,
          content: "export default function App() {\n  return (\n    <div className=\"app\">\n      <h1>Boss Built</h1>\n      <p>Generated by Genesis Swarm</p>\n    </div>\n  );\n}\n",
        },
      },
    },
    {
      delay: 500,
      ev: {
        type: "file_write",
        agentKey: "worker",
        content: "src/lib/auth.ts",
        data: { path: "src/lib/auth.ts", status: "wrote", lines: 64 },
      },
    },
    { delay: 200, ev: { type: "agent_complete", agentKey: "worker", agentName: "Worker" } },
    { delay: 200, ev: { type: "layer_complete", layer: 4, content: "Workers complete — 2 files produced." } },
    { delay: 300, ev: { type: "layer_start", layer: 5, content: "Critic Ring online." } },
    {
      delay: 150,
      ev: {
        type: "agent_start",
        agentKey: "bughunter",
        agentName: "BugHunter",
        content: "I'm actively trying to break what we just built.",
      },
    },
    {
      delay: 800,
      ev: {
        type: "guardian_finding",
        agentKey: "bughunter",
        agentName: "BugHunter",
        content: "MED: Add rate limit on login endpoint before production.",
        data: { severity: "MED" },
      },
    },
    { delay: 300, ev: { type: "agent_complete", agentKey: "bughunter", agentName: "BugHunter" } },
    { delay: 200, ev: { type: "layer_complete", layer: 5, content: "Critic Ring pass complete." } },
    { delay: 200, ev: { type: "layer_start", layer: 6, content: "Synthesizer merging outputs." } },
    {
      delay: 100,
      ev: { type: "agent_start", agentKey: "synthesizer", agentName: "Synthesizer", content: "Merging into one coherent package." },
    },
    { delay: 400, ev: { type: "agent_complete", agentKey: "synthesizer", agentName: "Synthesizer" } },
    { delay: 150, ev: { type: "layer_start", layer: 7, content: "Validator final gate." } },
    {
      delay: 100,
      ev: { type: "agent_start", agentKey: "validator", agentName: "Validator", content: "Last checkpoint — ready for export." },
    },
    { delay: 400, ev: { type: "agent_complete", agentKey: "validator", agentName: "Validator" } },
    {
      delay: 200,
      ev: {
        type: "done",
        content: "Genesis pass complete. Vector memory updated for the next turn.",
      },
    },
  ];

  for (const step of steps) {
    if (step.delay) await wait(step.delay);
    onEvent(step.ev);
  }
}
